version: "3.5"
services:
  db:
    image: postgres:12
    env_file:
      - .env.dev
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - internal-network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
    - 5050:5050
    env_file:
      - .env.dev
    networks:
      - internal-network

  {{cookiecutter.project_slug}}:
    image: {{cookiecutter.project_slug}}
    build: .
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - .:/app
    ports:
      - {{cookiecutter.django_port_for_dev}}:80
    env_file:
      - .env.dev
    command: ['bash', '/app/scripts/run_dev.sh']
    networks:
      - internal-network

  redis:
    image: redis
    networks:
        - internal-network
    
  celery:
    restart: always
    build: .
    command: celery -A {{cookiecutter.project_slug}} worker -l info
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
      - {{cookiecutter.project_slug}}
    networks:
      - internal-network

  flower:
    image: mher/flower:0.9.5
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db
    networks:
      - internal-network


volumes:
  db-data:

networks:
  internal-network:
    external: false
