version: "3.5"
services:
  db:
    image: postgres:12
    volumes:
      - ext-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5431:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=internal_software
      - POSTGRES_PORT=5432

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 5050:5050
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=dev@admin.com
      - PGADMIN_DEFAULT_PASSWORD=dev


volumes:
  ext-db-data: